final Map<String, Map<String, String>> translations = {
  'en_US': {
    "app_name": "Bharat Worker",
    "language": "Language",
    "onboarding_title_1": "Turn Your Skills into Income",
    "onboarding_desc_1":
        "Join thousands of skilled professionals offering services and growing their careers on Bharat Worker.",
    "onboarding_title_2": "Work When You Want",
    "onboarding_desc_2":
        "Accept jobs that fit your timing. Choose instant bookings or bid for high-value projects.",
    "onboarding_title_3": "Get Paid Fast & Fair",
    "onboarding_desc_3":
        "Track your earnings in real-time, withdraw instantly, and earn bonuses for great performance.",
    "onboarding_title_4": "Grow, Learn & Get Certified",
    "onboarding_desc_4":
        "Access training, get verified, and unlock higher-paying jobs with performance-based rewards.",
    "next": "Next",
    "get_started": "Get Started",
    "lets_you_in": "Let's you in",
    "continue_with_google": "Continue with Google",
    "continue_with_facebook": "Continue with Facebook",
    "continue_with_number": "Continue with Number",
    "already_have_account": "Already have an account?",
    "log_in": "Log in",
    "dont_have_account": "Don't have an account?",
    "sign_up": "Sign up",
    "welcome_to": "Welcome to",
    "welcome_subtitle": "Your trusted platform to find skilled jobs nearby.",
    "phone_number": "Phone Number",
    "or_continue_with": "Or continue with",
    "google": "Google",
    "facebook": "Facebook",
    "welcomeToBharatWorker": "Welcome to Bharat Worker",
    "createAnAccount": "Create an account",
    "createAccountDes":
        "Access training, get verified, and unlock higher-paying jobs with performance-based rewards.",
    "tell_us_about_you": "Tell Us About You",
    "help_customers_know": "Help customers know who you are.",
    "full_name": "Full Name",
    "date_of_birth": "Date of Birth",
    "mobile_number": "Mobile Number",
    "email": "Email",
    "verification_code": "Verification Code",
    "otp_sent_to": "We've sent a 6-digit OTP to",
    "wrong_otp": "Wrong OTP entered",
    "code_expires_in": "Code expires in",
    "did_not_receive_otp": "Did not receive OTP? ",
    "resend_code": "Resend Code",
    "please_fill_all_fields": "Please fill all fields",
    "profile_saved": "Profile saved!",
    "what_services_offer": "What Services Do You Offer?",
    "choose_categories_skilled": "Choose the categories you're skilled in.",
    "search_service_hint": "Search Service Plumber, Electrician etc.",
    "ac_repair": "AC Repair",
    "beauty": "Beauty",
    "appliance": "Appliance",
    "painter": "Painter",
    "cleaning": "Cleaning",
    "plumber": "Plumber",
    "electrician": "Electrician",
    "shifting": "Shifting",
    "mens_salon": "Men's Salon",
    "others": "Others",
    "enter_other_service": "Enter other service",
    "where_do_you_work": "Where Do You Work?",
    "verify_your_identity": "Verify Your Identity",
    "upload_your_id": "Upload your ID and certificates to get verified faster.",
    "choose_areas_to_accept_jobs":
        "Choose the areas where you can accept jobs.",
    "address": "Address",
    "enter_address": "Enter Address",
    "country": "Country",
    "state": "State",
    "select_state": "Select state",
    "city_town": "City / Town",
    "enter_city": "Enter City",
    "pin_code": "Pin Code",
    "enter_pin": "Enter Pin",
    "service_areas_distance": "Service Areas Distance",
    "save_and_continue": "Save & Continue",
    // Dashboard translations
    "home": "Home",
    "booking": "Booking",
    "explore": "Explore",
    "message": "Message",
    "settings": "Settings",
    "hi_user": "Hi, %s!",
    "find_quick_jobs": "Find Quick Jobs\nNear You",
    "quick_jobs_subtitle":
        "No waiting. No hassle.\nJust accept, serve, and earn.",
    "read_more": "Read More",
    "complete_profile": "Complete your profile!",
    "profile_completion": "Your profile has complete %s%",
    "todays_summary": "Today's Summary",
    "jobs_accepted": "Jobs Accepted",
    "earnings_today": "Earnings Today",
    "jobs_rating": "Jobs Rating",
    "job_matches": "Job Match With You (%s)",
    "view_more": "View more",
    "notifications": "Notifications",
    "job_accepted_successfully": "Job Accepted Successfully",
    "job_details": "Job Details",
    "job_id": "Job ID",
    "category": "Category",
    "ac_service": "AC Service",
    "date_time": "Date & Time",
    "location": "Location",
    "job_accept_success_msg":
        "You have successfully accepted this job. Please reach the location on time and follow all customer instructions.",
    "ac_balcony": "The AC is on the balcony.",
    "bring_ladder_kit": "Please bring your ladder and cleaning kit.",
    "call_before_arriving": "Call before arriving.",
    "my_payments": "My Payments",
    "training_certification": "Training & Certification",
    "notification": "Notification",
    "privacy_security": "Privacy & Security",
    "help_support": "Help & Support",
    "share_app": "Share App",
    "logout": "Logout",
    "profile_completion": "%s Complete",
    "phone_number": "Phone Number",
    "profile_name": "Akshay Swami",
    "settings_profile_completion": "Profile Completion",
    "verify_your_identity": "Verify Your Identity",
    "upload_id_certificates":
        "Upload your ID and certificates to get verified faster.",
    "select_government_id": "Select Government ID",
    "enter_id_no": "Enter ID No.",
    "enter_id_number": "Enter ID Number",
    "front_side": "Front Side",
    "back_side": "Back Side",
    "work_license_certificates": "Work License or Certificates",
    "upload_id_image": "upload ID Image",
    "remove": "Remove",
    "documents_reviewed":
        "Documents will be reviewed by the admin within 24 hours.",
    "aadhaar_12_digits": "Aadhaar must be 12 digits",
    "aadhaar_digits_only": "Aadhaar must be digits only",
    "pan_10_characters": "PAN must be 10 characters",
    "pan_format": "PAN format: 5 letters, 4 digits, 1 letter (e.g. ABCDE1234F)",
    "dl_valid": "Enter valid License number",
    "dl_format": "DL format: 2 letters, 2 digits, 8-13 letters/digits",
    "edit_profile": "Edit Profile",
    "general": "General",
    "service": "Service",
    "document": "Document",
    "profile_settings": "Profile Settings",
    "youre_ready_enjoy": "You're Ready – Enjoy!",
    "profile_100_complete":
        "Profile 100% Complete. Enjoy full access to jobs and earnings.",
    "please_review_details":
        "Please review your details before submitting for approval.",
    "your_application_is_under":
        "Your application is under review. Please wait for approval.",
    "professional_info": "Professional Info",
    "professional_information": "Professional Information",
    "service_categories": "Service Categories",
    "availability": "Availability",
    "service_area": "Service Area",
    "service_range": "Service Range",
    "referral_code": "Referral Code",
    "experience": "Experience",
    "rating": "Rating",
    "submit_for_approval": "Submit for Approval",
    "job_detail": "Job Detail",
    "job_id": "Job ID: ",
    "your_budget": "Your Budget",
    "edit_job": "Edit Job",
    "cancel_job": "Cancel Job",
    "job_description": "Job Description",
    "partner_performance": "Partner Performance",
    "customer_rating": "Customer Rating",
    "time_taken": "Time Taken",
    "service_quality": "Service Quality",
    "total_payment_summary": "Total Payment Summary",
    "additional_notes": "Additional Notes:",
    "user_budget": "User Budget:",
    "accepted_tab_description":
        "The customer is experiencing a continuous water leak from the kitchen tap. The leak has worsened over the past few days and is affecting daily use. The tap may need washer or seal replacement, or tightening of the connection pipe. The area is accessible, and the main water valve is nearby and can be shut off during the repair. The client expects a clean, quick fix with minimal disruption to the kitchen area. If additional parts are needed, the partner should inform the customer before purchase.",
    "accepted_tab_note_1": "Customer available between 2 PM – 5 PM",
    "accepted_tab_note_2": "Parking available",
    "accepted_tab_note_3": "Use back entrance for access",
    "accepted_tab_user_budget": "User Budget: ₹550",
    "accepted_tab_location": "Location details here...",
    "accepted_tab_schedule": "Schedule details here...",
    "edit_job_details": "Edit Job Details",
    "edit_job_subtitle":
        "Update your job preferences if something has changed. Kindly inform the customer if there is a time change.",
    "your_budget_placeholder": "e.g. ₹500",
    "available_time_slot": "Available Time Slot",
    "optional": "(Optional)",
    "available_time_slot_placeholder": "Available after 4:30 PM",
    "your_message": "Your Message",
    "your_message_placeholder": "I may arrive 15 mins late due to traffic.",
    "save_changes": "Save Changes",
    "congratulations": "Congratulations!",
    "job_update_success": "You've updated the job details successfully.",
    "explore_jobs": "Explore Jobs",
    "about_to_cancel_job": "You're About to Cancel This Job",
    "cancel_job_warning":
        "Canceling jobs after acceptance may affect your rating and priority for future bookings.",
    "why_cancelling": "Please Tell Us Why You're Cancelling",
    "cancel_reason_placeholder":
        "I have an emergency and won't be able to reach the location.",
    "go_back": "Go Back",
    "confirm_cancellation": "Confirm Cancellation",
    "job_cancelled": "Job Cancelled",
    "job_cancelled_success": "You've cancelled the job successfully.",
    "description": "Description",
    "schedule": "Schedule",
    "navigation_map_title": "Map",
    "aadhar_card": "Aadhar card",
    "pan_card": "PAN Card",
    "skip": "Skip",
    "pe": "Pe",
    "phone_pe": "PhonePe",
    "pg": "PG",
    "bharat_worker": "Bharat Worker",
    "one_item": "1 item",
    "upi_id": "UPI ID",
    "use_upi_for_quick_payments": "Use UPI for quick payments",
    "net_banking": "Net Banking",
    "select_from_a_list_of_banks": "Select from a list of banks",
    "credit_debit_cards": "Credit & Debit Cards",
    "save_and_pay_via_cards": "Save & pay via cards",
    "see_more": "See more",
    "to_pay": "To Pay",
    "pay_now": "Pay now",
    "your_kyc_is_approved":
        "Your KYC is approved! You're now ready to start earning.",
    "your_almost_there":
        "You're almost there. Add remaining details to complete your profile.",
    "profile": "Profile",
    "complete": "Complete",
    "greatYourProfileIsReady":
        "Great! Your profile is ready. Submit now to get verified and start getting jobs.",
    "viewProfile": "View Profile",
    "underReview": "Under Review",
    "profileSubmittedUnderReview":
        "Profile submitted. Under review — you'll be notified once approved.",
    "submitForApproval": "Submit for Approval",
    "exploreJobs": "Explore Jobs",
    "verifiedPartner": "Verified Partner",
    "congratulationsYourAccountIsVerified":
        "Congratulations! Your account is verified. Start exploring job opportunities now.",
    "yourAvailabilityStatus": "Your Availability Status",
    "letUsersKnowWhenYou": "Let users know when you're ready for work.",
    // Subscription Management
    "my_subscription": "My Subscription",
    "pro_plan": "Pro Plan",
    "premium_pro": "Premium Pro",
    "elite_partner": "Elite Partner",
    "expiry_date": "Expiry Date",
    "remaining_days": "Remaining Days",
    "days": "days",
    "active": "Active",
    "scheduled": "Scheduled",
    "benefits": "Benefits",
    "unlimited_jobs": "Unlimited Jobs",
    "premium_profile": "Premium Profile",
    "support_24_7": "24/7 Support",
    "zero_commission_first_5": "0% commission on first 5 jobs",
    "change_plan": "Change Plan",
    "renew_plan": "Renew Plan",
    "upcoming_plan": "Upcoming Plan",
    "start_date": "Start Date",
    "upcoming_plan_note":
        "Your upcoming plan will auto-activate once the current plan expires.",
    "no_upcoming_plans": "No upcoming plans scheduled",
    "subscription_expired": "Subscription Expired",
    "subscription_expired_message":
        "Your subscription has expired. Please renew to access new jobs.",
    "buy_plan": "Buy Plan"
  },
  'zh_CN': {
    "app_name": "Bharat Worker",
    "language": "Language",
    "onboarding_title_1": "Turn Your Skills into Income",
    "onboarding_desc_1":
        "Join thousands of skilled professionals offering services and growing their careers on Bharat Worker.",
    "onboarding_title_2": "Work When You Want",
    "onboarding_desc_2":
        "Accept jobs that fit your timing. Choose instant bookings or bid for high-value projects.",
    "onboarding_title_3": "Get Paid Fast & Fair",
    "onboarding_desc_3":
        "Track your earnings in real-time, withdraw instantly, and earn bonuses for great performance.",
    "onboarding_title_4": "Grow, Learn & Get Certified",
    "onboarding_desc_4":
        "Access training, get verified, and unlock higher-paying jobs with performance-based rewards.",
    "next": "Next",
    "get_started": "Set Started",
    "lets_you_in": "Let's you in",
    "continue_with_google": "Continue with Google",
    "continue_with_facebook": "Continue with Facebook",
    "continue_with_number": "Continue with Number",
    "already_have_account": "Already have an account?",
    "log_in": "Log in",
    "dont_have_account": "Don't have an account?",
    "sign_up": "Sign up",
    "welcome_to": "Welcome to",
    "welcome_subtitle": "Your trusted platform to find skilled jobs nearby.",
    "phone_number": "Phone Number",
    "or_continue_with": "Or continue with",
    "google": "Google",
    "facebook": "Facebook",
    "tell_us_about_you": "Tell Us About You",
    "help_customers_know": "Help customers know who you are.",
    "full_name": "Full Name",
    "date_of_birth": "Date of Birth",
    "mobile_number": "Mobile Number",
    "email": "Email",
    "verification_code": "Verification Code",
    "otp_sent_to": "We've sent a 6-digit OTP to",
    "wrong_otp": "Wrong OTP entered",
    "code_expires_in": "Code expires in",
    "did_not_receive_otp": "Did not receive OTP? ",
    "resend_code": "Resend Code",
    "please_fill_all_fields": "Please fill all fields",
    "profile_saved": "Profile saved!",
    "what_services_offer": "What Services Do You Offer?",
    "choose_categories_skilled": "Choose the categories you're skilled in.",
    "search_service_hint": "Search Service Plumber, Electrician etc.",
    "ac_repair": "AC Repair",
    "beauty": "Beauty",
    "appliance": "Appliance",
    "painter": "Painter",
    "cleaning": "Cleaning",
    "plumber": "Plumber",
    "electrician": "Electrician",
    "shifting": "Shifting",
    "mens_salon": "Men's Salon",
    "others": "Others",
    "enter_other_service": "Enter other service",
    "where_do_you_work": "Where Do You Work?",
    "choose_areas_to_accept_jobs":
        "Choose the areas where you can accept jobs.",
    "address": "Address",
    "enter_address": "Enter Address",
    "country": "Country",
    "state": "State",
    "select_state": "Select state",
    "city_town": "City / Town",
    "enter_city": "Enter City",
    "pin_code": "Pin Code",
    "enter_pin": "Enter Pin",
    "service_areas_distance": "Service Areas Distance",
    "save_and_continue": "Save & Continue",
    // Add new dashboard translations for Chinese
    "home": "首页",
    "booking": "预约",
    "explore": "探索",
    "message": "消息",
    "settings": "设置",
    "hi_user": "你好, %s!",
    "find_quick_jobs": "在您附近找到快速工作",
    "quick_jobs_subtitle": "无需等待。没有麻烦。\n只需接受、服务和赚钱。",
    "read_more": "阅读更多",
    "complete_profile": "完成您的个人资料！",
    "profile_completion": "您的个人资料已完成 %s%",
    "todays_summary": "今日总结",
    "jobs_accepted": "已接受的工作",
    "earnings_today": "今日收入",
    "jobs_rating": "工作评分",
    "job_matches": "与您匹配的工作 (%s)",
    "view_more": "查看更多",
    "notifications": "通知",
    "job_accepted_successfully": "工作已成功接受",
    "job_details": "工作详情",
    "job_id": "工作编号",
    "category": "类别",
    "ac_service": "空调服务",
    "date_time": "日期和时间",
    "location": "地点",
    "job_accept_success_msg": "您已成功接受此工作。请准时到达并遵循所有客户指示。",
    "ac_balcony": "空调在阳台上。",
    "bring_ladder_kit": "请带上您的梯子和清洁工具。",
    "call_before_arriving": "到达前请致电。",
    "my_payments": "我的付款",
    "training_certification": "培训与认证",
    "notification": "通知",
    "privacy_security": "隐私与安全",
    "help_support": "帮助与支持",
    "share_app": "分享应用",
    "logout": "登出",
    "profile_completion": "%s 完成",
    "phone_number": "电话号码",
    "profile_name": "Akshay Swami",
    "settings_profile_completion": "个人资料完成度",
    "verify_your_identity": "Verify Your Identity",
    "upload_id_certificates":
        "Upload your ID and certificates to get verified faster.",
    "select_government_id": "Select Government ID",
    "enter_id_no": "Enter ID No.",
    "enter_id_number": "Enter ID Number",
    "front_side": "Front Side",
    "back_side": "Back Side",
    "work_license_certificates": "Work License or Certificates",
    "upload_id_image": "upload ID Image",
    "remove": "Remove",
    "documents_reviewed":
        "Documents will be reviewed by the admin within 24 hours.",
    "aadhaar_12_digits": "Aadhaar must be 12 digits",
    "aadhaar_digits_only": "Aadhaar must be digits only",
    "pan_10_characters": "PAN must be 10 characters",
    "pan_format": "PAN format: 5 letters, 4 digits, 1 letter (e.g. ABCDE1234F)",
    "dl_valid": "Enter valid License number",
    "dl_format": "DL format: 2 letters, 2 digits, 8-13 letters/digits",
    "edit_profile": "Edit Profile",
    "general": "General",
    "service": "Service",
    "document": "Document",
    "profile": "Profile Settings",
    "profile_settings": "Profile Settings",
    "youre_ready_enjoy": "You're Ready – Enjoy!",
    "profile_100_complete":
        "Profile 100% Complete. Enjoy full access to jobs and earnings.",
    "please_review_details":
        "Please review your details before submitting for approval.",
    "your_application_is_under":
        "Your application is under review. Please wait for approval.",
    "professional_info": "Professional Info",
    "professional_information": "Professional Information",
    "service_categories": "Service Categories",
    "availability": "Availability",
    "service_area": "Service Area",
    "service_range": "Service Range",
    "experience": "Experience",
    "rating": "Rating",
    "submit_for_approval": "Submit for Approval",
    "job_detail": "Job Detail",
    "job_id": "Job ID: #1023",
    "your_budget": "Your Budget",
    "edit_job": "Edit Job",
    "cancel_job": "Cancel Job",
    "job_description": "Job Description",
    "partner_performance": "Partner Performance",
    "customer_rating": "Customer Rating",
    "time_taken": "Time Taken",
    "service_quality": "Service Quality",
    "total_payment_summary": "Total Payment Summary",
    "additional_notes": "Additional Notes:",
    "user_budget": "User Budget:",
    "accepted_tab_description":
        "The customer is experiencing a continuous water leak from the kitchen tap. The leak has worsened over the past few days and is affecting daily use. The tap may need washer or seal replacement, or tightening of the connection pipe. The area is accessible, and the main water valve is nearby and can be shut off during the repair. The client expects a clean, quick fix with minimal disruption to the kitchen area. If additional parts are needed, the partner should inform the customer before purchase.",
    "accepted_tab_note_1": "Customer available between 2 PM – 5 PM",
    "accepted_tab_note_2": "Parking available",
    "accepted_tab_note_3": "Use back entrance for access",
    "accepted_tab_user_budget": "User Budget: ₹550",
    "accepted_tab_location": "Location details here...",
    "accepted_tab_schedule": "Schedule details here...",
    "edit_job_details": "Edit Job Details",
    "edit_job_subtitle":
        "Update your job preferences if something has changed. Kindly inform the customer if there is a time change.",
    "your_budget_placeholder": "e.g. ₹500",
    "available_time_slot": "Available Time Slot",
    "optional": "(Optional)",
    "available_time_slot_placeholder": "Available after 4:30 PM",
    "your_message": "Your Message",
    "your_message_placeholder": "I may arrive 15 mins late due to traffic.",
    "save_changes": "Save Changes",
    "congratulations": "Congratulations!",
    "job_update_success": "You've updated the job details successfully.",
    "explore_jobs": "Explore Jobs",
    "about_to_cancel_job": "You're About to Cancel This Job",
    "cancel_job_warning":
        "Canceling jobs after acceptance may affect your rating and priority for future bookings.",
    "why_cancelling": "Please Tell Us Why You're Cancelling",
    "cancel_reason_placeholder":
        "I have an emergency and won't be able to reach the location.",
    "go_back": "Go Back",
    "confirm_cancellation": "Confirm Cancellation",
    "job_cancelled": "Job Cancelled",
    "job_cancelled_success": "You've cancelled the job successfully.",
    "description": "Description",
    "schedule": "Schedule",
    "navigation_map_title": "地图",
    "pe": "Pe",
    "phone_pe": "PhonePe",
    "pg": "PG",
    "bharat_worker": "Bharat Worker",
    "one_item": "1 item",
    "upi_id": "UPI ID",
    "use_upi_for_quick_payments": "Use UPI for quick payments",
    "net_banking": "Net Banking",
    "select_from_a_list_of_banks": "Select from a list of banks",
    "credit_debit_cards": "Credit & Debit Cards",
    "save_and_pay_via_cards": "Save & pay via cards",
    "see_more": "See more",
    "to_pay": "To Pay",
    "pay_now": "Pay now",
    // Subscription Management
    "my_subscription": "我的订阅",
    "pro_plan": "专业计划",
    "premium_pro": "高级专业版",
    "elite_partner": "精英合作伙伴",
    "expiry_date": "到期日期",
    "remaining_days": "剩余天数",
    "days": "天",
    "active": "活跃",
    "scheduled": "已安排",
    "benefits": "福利",
    "unlimited_jobs": "无限工作",
    "premium_profile": "高级档案",
    "support_24_7": "24/7 支持",
    "zero_commission_first_5": "前5个工作0%佣金",
    "change_plan": "更改计划",
    "renew_plan": "续订计划",
    "upcoming_plan": "即将推出的计划",
    "start_date": "开始日期",
    "upcoming_plan_note": "当前计划到期后，您的即将推出的计划将自动激活。",
    "no_upcoming_plans": "没有安排即将推出的计划",
    "subscription_expired": "订阅已过期",
    "subscription_expired_message": "您的订阅已过期。请续订以访问新工作。",
    "buy_plan": "购买计划"
  },
  'hi_IN': {
    "app_name": "Bharat Worker",
    "language": "Language",
    "onboarding_title_1": "Turn Your Skills into Income",
    "onboarding_desc_1":
        "Join thousands of skilled professionals offering services and growing their careers on Bharat Worker.",
    "onboarding_title_2": "Work When You Want",
    "onboarding_desc_2":
        "Accept jobs that fit your timing. Choose instant bookings or bid for high-value projects.",
    "onboarding_title_3": "Get Paid Fast & Fair",
    "onboarding_desc_3":
        "Track your earnings in real-time, withdraw instantly, and earn bonuses for great performance.",
    "onboarding_title_4": "Grow, Learn & Get Certified",
    "onboarding_desc_4":
        "Access training, get verified, and unlock higher-paying jobs with performance-based rewards.",
    "next": "Next",
    "get_started": "Set Started",
    "lets_you_in": "Let's you in",
    "continue_with_google": "Continue with Google",
    "continue_with_facebook": "Continue with Facebook",
    "continue_with_number": "Continue with Number",
    "already_have_account": "Already have an account?",
    "log_in": "Log in",
    "dont_have_account": "Don't have an account?",
    "sign_up": "Sign up",
    "welcome_to": "Welcome to",
    "welcome_subtitle": "Your trusted platform to find skilled jobs nearby.",
    "phone_number": "Phone Number",
    "or_continue_with": "Or continue with",
    "google": "Google",
    "facebook": "Facebook",
    "welcomeToBharatWorker": "Welcome to Bharat Worker",
    "createAnAccount": "Create an account",
    "createAccountDes":
        "Access training, get verified, and unlock higher-paying jobs with performance-based rewards.",
    "tell_us_about_you": "Tell Us About You",
    "help_customers_know": "Help customers know who you are.",
    "full_name": "Full Name",
    "date_of_birth": "Date of Birth",
    "mobile_number": "Mobile Number",
    "email": "Email",
    "verification_code": "Verification Code",
    "otp_sent_to": "We've sent a 6-digit OTP to",
    "wrong_otp": "Wrong OTP entered",
    "code_expires_in": "Code expires in",
    "did_not_receive_otp": "Did not receive OTP? ",
    "resend_code": "Resend Code",
    "please_fill_all_fields": "Please fill all fields",
    "profile_saved": "Profile saved!",
    "what_services_offer": "What Services Do You Offer?",
    "choose_categories_skilled": "Choose the categories you're skilled in.",
    "search_service_hint": "Search Service Plumber, Electrician etc.",
    "ac_repair": "AC Repair",
    "beauty": "Beauty",
    "appliance": "Appliance",
    "painter": "Painter",
    "cleaning": "Cleaning",
    "plumber": "Plumber",
    "electrician": "Electrician",
    "shifting": "Shifting",
    "mens_salon": "Men's Salon",
    "others": "Others",
    "enter_other_service": "Enter other service",
    "where_do_you_work": "Where Do You Work?",
    "choose_areas_to_accept_jobs":
        "Choose the areas where you can accept jobs.",
    "address": "Address",
    "enter_address": "Enter Address",
    "country": "Country",
    "state": "State",
    "select_state": "Select state",
    "city_town": "City / Town",
    "enter_city": "Enter City",
    "pin_code": "Pin Code",
    "enter_pin": "Enter Pin",
    "service_areas_distance": "Service Areas Distance",
    "save_and_continue": "Save & Continue",
    // Dashboard translations
    "home": "Home",
    "booking": "Booking",
    "explore": "Explore",
    "message": "Message",
    "settings": "Settings",
    "hi_user": "Hi, %s!",
    "find_quick_jobs": "Find Quick Jobs\nNear You",
    "quick_jobs_subtitle":
        "No waiting. No hassle.\nJust accept, serve, and earn.",
    "read_more": "Read More",
    "complete_profile": "Complete your profile!",
    "profile_completion": "Your profile has complete %s%",
    "todays_summary": "Today's Summary",
    "jobs_accepted": "Jobs Accepted",
    "earnings_today": "Earnings Today",
    "jobs_rating": "Jobs Rating",
    "job_matches": "Job Match With You (%s)",
    "view_more": "View more",
    "notifications": "Notifications",
    "job_accepted_successfully": "Job Accepted Successfully",
    "job_details": "Job Details",
    "job_id": "Job ID",
    "category": "Category",
    "ac_service": "AC Service",
    "date_time": "Date & Time",
    "location": "Location",
    "job_accept_success_msg":
        "You have successfully accepted this job. Please reach the location on time and follow all customer instructions.",
    "ac_balcony": "The AC is on the balcony.",
    "bring_ladder_kit": "Please bring your ladder and cleaning kit.",
    "call_before_arriving": "Call before arriving.",
    "my_payments": "My Payments",
    "training_certification": "Training & Certification",
    "notification": "Notification",
    "privacy_security": "Privacy & Security",
    "help_support": "Help & Support",
    "share_app": "Share App",
    "logout": "Logout",
    // "profile_completion": "%s Complete",
    // "phone_number": "Phone Number",
    "profile_name": "Akshay Swami",
    "settings_profile_completion": "Profile Completion",
    "verify_your_identity": "Verify Your Identity",
    "upload_id_certificates":
        "Upload your ID and certificates to get verified faster.",
    "select_government_id": "Select Government ID",
    "enter_id_no": "Enter ID No.",
    "enter_id_number": "Enter ID Number",
    "front_side": "Front Side",
    "back_side": "Back Side",
    "work_license_certificates": "Work License or Certificates",
    "upload_id_image": "upload ID Image",
    "remove": "Remove",
    "documents_reviewed":
        "Documents will be reviewed by the admin within 24 hours.",
    "aadhaar_12_digits": "Aadhaar must be 12 digits",
    "aadhaar_digits_only": "Aadhaar must be digits only",
    "pan_10_characters": "PAN must be 10 characters",
    "pan_format": "PAN format: 5 letters, 4 digits, 1 letter (e.g. ABCDE1234F)",
    "dl_valid": "Enter valid License number",
    "dl_format": "DL format: 2 letters, 2 digits, 8-13 letters/digits",
    "edit_profile": "Edit Profile",
    "general": "General",
    "service": "Service",
    "document": "Document",
    "profile": "Profile Settings",
    "profile_settings": "Profile Settings",
    "youre_ready_enjoy": "You're Ready – Enjoy!",
    "profile_100_complete":
        "Profile 100% Complete. Enjoy full access to jobs and earnings.",
    "please_review_details":
        "Please review your details before submitting for approval.",
    "professional_info": "Professional Info",
    "professional_information": "Professional Information",
    "service_categories": "Service Categories",
    "availability": "Availability",
    "service_area": "Service Area",
    "service_range": "Service Range",
    "referral_code": "रेफरल कोड",
    "experience": "Experience",
    "rating": "Rating",
    "submit_for_approval": "Submit for Approval",
    "job_detail": "Job Detail",
    // "job_id": "Job ID: #1023",
    "your_budget": "Your Budget",
    "edit_job": "Edit Job",
    "cancel_job": "Cancel Job",
    "job_description": "Job Description",
    "partner_performance": "Partner Performance",
    "customer_rating": "Customer Rating",
    "time_taken": "Time Taken",
    "service_quality": "Service Quality",
    "total_payment_summary": "Total Payment Summary",
    "additional_notes": "Additional Notes:",
    "user_budget": "User Budget:",
    "accepted_tab_description":
        "The customer is experiencing a continuous water leak from the kitchen tap. The leak has worsened over the past few days and is affecting daily use. The tap may need washer or seal replacement, or tightening of the connection pipe. The area is accessible, and the main water valve is nearby and can be shut off during the repair. The client expects a clean, quick fix with minimal disruption to the kitchen area. If additional parts are needed, the partner should inform the customer before purchase.",
    "accepted_tab_note_1": "Customer available between 2 PM – 5 PM",
    "accepted_tab_note_2": "Parking available",
    "accepted_tab_note_3": "Use back entrance for access",
    "accepted_tab_user_budget": "User Budget: ₹550",
    "accepted_tab_location": "Location details here...",
    "accepted_tab_schedule": "Schedule details here...",
    "edit_job_details": "Edit Job Details",
    "edit_job_subtitle":
        "Update your job preferences if something has changed. Kindly inform the customer if there is a time change.",
    "add_bid_subtitle": "Submit your bid for this job opportunity",
    "Submit Bid": "Submit Bid",
    "ok_got_it": "OK, Got It",
    "submitting_bid": "Submitting bid...",
    "cancelling_bid": "Cancelling bid...",
    "updating_job": "Updating job...",
    "your_budget_placeholder": "e.g. ₹500",
    "available_time_slot": "Available Time Slot",
    "optional": "(Optional)",
    "available_time_slot_placeholder": "Available after 4:30 PM",
    "your_message": "Your Message",
    "your_message_placeholder": "I may arrive 15 mins late due to traffic.",
    "save_changes": "Save Changes",
    "congratulations": "Congratulations!",
    "job_update_success": "You've updated the job details successfully.",
    "explore_jobs": "Explore Jobs",
    "about_to_cancel_job": "You're About to Cancel This Job",
    "cancel_job_warning":
        "Canceling jobs after acceptance may affect your rating and priority for future bookings.",
    "why_cancelling": "Please Tell Us Why You're Cancelling",
    "cancel_reason_placeholder": "Cancel reason",
    "go_back": "Go Back",
    "confirm_cancellation": "Confirm Cancellation",
    "job_cancelled": "Job Cancelled",
    "job_cancelled_success": "You've cancelled the job successfully.",
    "description": "Description",
    "schedule": "Schedule",
    "call": "Call",
    "savedJobs": "Saved Jobs",
    "addMoney": "Add Money",
    "pe": "पे",
    "phone_pe": "फोनपे",
    "pg": "पीजी",
    "bharat_worker": "भारत वर्कर",
    "one_item": "1 आइटम",
    "upi_id": "यूपीआई आईडी",
    "use_upi_for_quick_payments": "त्वरित भुगतान के लिए यूपीआई का उपयोग करें",
    "net_banking": "नेट बैंकिंग",
    "select_from_a_list_of_banks": "बैंकों की सूची से चुनें",
    "credit_debit_cards": "क्रेडिट और डेबिट कार्ड",
    "save_and_pay_via_cards": "कार्ड के माध्यम से सहेजें और भुगतान करें",
    "see_more": "और देखें",
    "to_pay": "भुगतान करने के लिए",
    "pay_now": "अभी भुगतान करें",
    // Subscription Management
    "my_subscription": "मेरी सदस्यता",
    "pro_plan": "प्रो प्लान",
    "premium_pro": "प्रीमियम प्रो",
    "elite_partner": "एलीट पार्टनर",
    "expiry_date": "समाप्ति तिथि",
    "remaining_days": "शेष दिन",
    "days": "दिन",
    "active": "सक्रिय",
    "scheduled": "अनुसूचित",
    "benefits": "लाभ",
    "unlimited_jobs": "असीमित नौकरियां",
    "premium_profile": "प्रीमियम प्रोफाइल",
    "support_24_7": "24/7 सहायता",
    "zero_commission_first_5": "पहले 5 नौकरियों पर 0% कमीशन",
    "change_plan": "योजना बदलें",
    "renew_plan": "योजना नवीनीकरण",
    "upcoming_plan": "आगामी योजना",
    "start_date": "प्रारंभ तिथि",
    "upcoming_plan_note":
        "वर्तमान योजना समाप्त होने के बाद आपकी आगामी योजना स्वचालित रूप से सक्रिय हो जाएगी।",
    "no_upcoming_plans": "कोई आगामी योजना निर्धारित नहीं है",
    "subscription_expired": "सदस्यता समाप्त",
    "subscription_expired_message":
        "आपकी सदस्यता समाप्त हो गई है। कृपया नई नौकरियों तक पहुंचने के लिए नवीनीकरण करें।",
    "buy_plan": "योजना खरीदें"
  },
};

final List<Map<String, String>> supportedLanguages = [
  {"code": "en", "name": "English"},
  {"code": "hi", "name": "हिन्दी"},
  {"code": "hinglish", "name": "Hinglish"},
  {"code": "bn", "name": "বাংলা"},
  {"code": "te", "name": "తెలుగు"},
  {"code": "mr", "name": "मराठी"},
  {"code": "ta", "name": "தமிழ்"},
  {"code": "gu", "name": "ગુજરાતી"},
  {"code": "ur", "name": "اردو"},
  {"code": "kn", "name": "ಕನ್ನಡ"},
  {"code": "ml", "name": "മലയാളം"},
  {"code": "as", "name": "অসমীয়া"},
];
